# Generated by Django 6.0.1 on 2026-02-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pdf_resource',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='Ex: 2h, 45min', max_length=50),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
